<a href="https://colab.research.google.com/github/igormcsouza/analise-de-dados-em-python/blob/master/Bibliotecas_B%C3%A1sicas_de_An%C3%A1lise_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Numpy - Numerical Python
https://docs.scipy.org/doc/numpy/reference/

In [3]:
import numpy as np
matrix = np.random.random((10000, 384)).astype(np.float32)
matrix

array([[0.6297827 , 0.18374817, 0.9822263 , ..., 0.3165087 , 0.69446605,
        0.48319447],
       [0.4962016 , 0.33761066, 0.5238337 , ..., 0.78581387, 0.37205288,
        0.4838938 ],
       [0.8021601 , 0.7751329 , 0.86167586, ..., 0.0996724 , 0.7499254 ,
        0.6509813 ],
       ...,
       [0.49043036, 0.9312415 , 0.47936332, ..., 0.4702403 , 0.7254487 ,
        0.56154567],
       [0.22819546, 0.17126067, 0.5882215 , ..., 0.2939573 , 0.6133932 ,
        0.72214353],
       [0.1261184 , 0.7036425 , 0.20204772, ..., 0.77914876, 0.27475408,
        0.6152215 ]], dtype=float32)

In [15]:
an=np.array(range(1,7))
print(an)
print(an.ndim)
print(an.shape)

[1 2 3 4 5 6]
1
(6,)


In [16]:
an2=an.reshape(2,3)
print(an2)
print(an2.ndim)
print(an2.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [10]:
an2[1][0:2]   # a slice: As primeiras duas colunas e a ultima linha

array([4, 5])

In [18]:
k=np.array([2, 3])
print(k.shape)
print(k.dot(an2) )

(2,)
[14 19 24]


# 2. Pandas 
https://pandas.pydata.org/pandas-docs/stable/

http://manishamde.github.io/blog/2013/03/07/pandas-and-python-top-10/

In [20]:
from pandas import DataFrame, Series

df = DataFrame({'int_col' : [1,2,6,8,-1], 'float_col' : [0.1, 0.2,0.2,10.1,None], 'str_col' : ['a','b',None,'c','a']})
df

int_col  float_col str_col
0        1        0.1       a
1        2        0.2       b
2        6        0.2    None
3        8       10.1       c
4       -1        NaN       a

In [22]:
df.loc[:,['float_col','int_col']]

float_col  int_col
0        0.1        1
1        0.2        2
2        0.2        6
3       10.1        8
4        NaN       -1

In [23]:
df[['float_col','int_col']]

float_col  int_col
0        0.1        1
1        0.2        2
2        0.2        6
3       10.1        8
4        NaN       -1

In [24]:
df[df['float_col'] > 0.15]

int_col  float_col str_col
1        2        0.2       b
2        6        0.2    None
3        8       10.1       c

In [25]:
df[df['float_col'] == 0.1]

int_col  float_col str_col
0        1        0.1       a

In [26]:
df[(df['float_col'] > 0.1) & (df['int_col']>2)]

int_col  float_col str_col
2        6        0.2    None
3        8       10.1       c

In [28]:
df2 = df.rename(columns={'int_col' : 'some_other_name'})
df2

some_other_name  float_col str_col
0                1        0.1       a
1                2        0.2       b
2                6        0.2    None
3                8       10.1       c
4               -1        NaN       a

In [31]:
df2 = df2.dropna()
df2

some_other_name  float_col str_col
0                1        0.1       a
1                2        0.2       b
3                8       10.1       c

In [32]:
df3 = df.copy()
mean = df3['float_col'].mean()
mean

2.65

In [34]:
df3 = df3['float_col'].fillna(mean)
df3

0     0.10
1     0.20
2     0.20
3    10.10
4     2.65
Name: float_col, dtype: float64

# 3. MatplotLib
https://matplotlib.org/3.1.1/contents.html

# 4. Scipy
https://www.scipy.org/docs.html

https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.linprog.html

In [0]:
c = [-1, 4]
A = [[-3, 1], [1, 2]]
b = [6, 4]
x0_bounds = (None, None)
x1_bounds = (-3, None)
from scipy.optimize import linprog
res = linprog(c, A_ub=A, b_ub=b, bounds=[x0_bounds, x1_bounds])

In [37]:
print(res)

     con: array([], dtype=float64)
     fun: -21.99999984082497
 message: 'Optimization terminated successfully.'
     nit: 6
   slack: array([3.89999997e+01, 8.46872172e-08])
  status: 0
 success: True
       x: array([ 9.99999989, -2.99999999])


In [38]:
res = linprog(c, A_ub=A, b_ub=b, bounds=[x0_bounds, x1_bounds], method='revised simplex')
print(res)

     con: array([], dtype=float64)
     fun: -22.0
 message: 'Optimization terminated successfully.'
     nit: 1
   slack: array([39.,  0.])
  status: 0
 success: True
       x: array([10., -3.])


# 5. pandas_profiling
https://pypi.org/project/pandas-profiling/

In [1]:
import pandas_profiling

In [ ]:
pandas_profiling.ProfileReport(df)